version: "3.9"

services:
  database:
    image: postgres
    container_name: database_node
    restart: always
    ports: 
      - 5432:5432
      - 9229:9229
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=node
      - POSTGRES_DB=shop_car_api_node
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: shop_car_api_node
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local